ajaxpage/urls.py
from django.urls import path
from .views import story8index,panggil_buku
#url for app

app_name = "story8"

urlpatterns = [
    path('', story8index,name ='story8index'),
    path('panggil_buku/',panggil_buku),
]

jspage/urls.py
from django.urls import path
from .views import index
#url for app

app_name = "jspage"

urlpatterns = [
    path('', index,name = 'index'),
]

lab6/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('jspage/', include('jspage.urls')),
    path('story8/', include('ajaxpage.urls')),
    path('story9/', include('story9.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('story10/',include('story10.urls')),
]

landingpage/urls.py
from django.urls import path
from .views import index
#url for app

app_name = "landingpage"

urlpatterns = [
    path('', index,name = 'index'),
]

story10/urls.py
from django.urls import path
from .views import index10
#url for app


urlpatterns = [
    path('', index10,name = 'index10'),
]

story9/urls.py
from django.urls import path
from .views import story9view,signup
#url for app


urlpatterns = [
    path('', story9view,name ='story9'),
    path('signup/', signup ,name ='signup'),
]

ajaxpage/models.py
from django.db import models

# Create your models here.

jspage/models.py
from django.db import models

# Create your models here.

landingpage/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class statusModel(models.Model):
    nama = models.CharField(max_length = 20)
    status = models.CharField(max_length = 300)
    waktu = models.DateTimeField(default = timezone.now)

story10/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

landingpage/forms.py
from django import forms

class statusForm(forms.Form):
    nama = forms.CharField(label = "Nama", max_length = 20)
    status = forms.CharField(label = "Status", max_length = 300)

ajaxpage/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests

# Create your views here.
def story8index(request):
    r = requests.get('https://www.googleapis.com/books/v1/volumes?q=naruto')
    return render(request,'story8index.html',{'data_buku':r.json()})

def panggil_buku(request):
    q = request.GET.get('q','Jaja')
    r = requests.get('https://www.googleapis.com/books/v1/volumes?q='+q)
    return JsonResponse(r.json())

jspage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

landingpage/views.py
from django.shortcuts import render,redirect
from .forms import statusForm
from .models import statusModel
# Create your views here.

def index(request):
    form = statusForm(request.POST or None)
    data = statusModel.objects.all().order_by('-id')
    isian = {
            'generated_formulir': form,
            'generated_model' : data
        }
    if request.method == 'POST':
        model = statusModel(nama = form['nama'].value(),status = form['status'].value())
        model.save()
        return redirect("landingpage:index")
    return render(request,'landingpage/index.html', isian)
    

story10/views.py
from django.shortcuts import render

# Create your views here.
def index10(request):
    return render(request,'index10.html')

story9/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

def story9view(request):
    if request.user.is_authenticated:
        context= {'name':request.user.username}
        return render (request, 'story9.html',context)
    else:
        return render(request,'story9.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {
        'form': form
    })

ajaxpage/templates/story8index.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    </head>
    <body>
        <script src="https://code.jquery.com/jquery-1.11.3.js" ></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <div style="text-align: center;">
            <h1 style="justify-items: center;">Perpustakaan </h1>
                <input  placeholder="Search" id="KotakPencarian">
                <button id="TombolSaya">Search</button>
        </div>   
        
        <div>
            <table class="align-items-center mx-auto mt-3 table table-bordered">
            <thead>
            <tr>
                <th>Thumbnail</th>
                <th>Judul</th>
                <th>Pengarang</th>
                <th>Deskripsi</th>
            </tr>
            </thead> 
            <tbody id = "data">
            {% for i in data_buku.items %}
            <tr>
              <td style="width: 10em;"><img src= "{{i.volumeInfo.imageLinks.thumbnail}}" alt="Tidak tersedia"></td>
              <td>{{i.volumeInfo.title}}</td>
              <td>{{i.volumeInfo.authors}}</td>
              <td>{{i.volumeInfo.description}}</td>
            </tr>
            {% endfor %}
            </tbody>
            </table>
        </div>

        <script>

        $("#TombolSaya").click(
            function() {
                var keyword = $("#KotakPencarian").val();
                $.ajax({
                    type: "GET",
                    dataType: "json",
                    url : "http://inisti6.herokuapp.com/story8/panggil_buku/?q="+keyword,
                    success: function (result) {
                        $("#data").empty();
                        for (let index = 0; index < 10; index++) {
                            var value = "<tr>";
                            // +function (result) {
                            if (result.items[index].volumeInfo.imageLinks==undefined) {
                                value +="<td>"+"None"+"</td>";
                                // $("#data").append("<td>"+"None"+"<td>");
                            } else {
                                value += "<td>"+"<img src ="+result.items[index].volumeInfo.imageLinks.thumbnail+" alt ='Tidak tersedia'>"+"</td>";
                                // $("#data").append("<td>"+"<img src ="+result.items[index].volumeInfo.imageLinks.thumbnail+" alt ='Tidak tersedia'>"+"</td>");
                            
                            }
                            // $("#data").append("<td>"+result.items[index].volumeInfo.title+"<td>");
                            value += "<td>"+result.items[index].volumeInfo.title+"</td>";
                            if (result.items[index].volumeInfo.authors == undefined) {
                            //    $("#data").append("<td> Tidak diketahui <td>");
                               value += "<td> Tidak diketahui </td>";
                            } else {
                                // $("#data").append("<ul><td>");
                                value += "<td><ul>";
                               for (let i = 0; i <result.items[index].volumeInfo.authors.length; i++) {
                                // $("#data").append("<li>"+result.items[index].volumeInfo.authors[i]+"</li>");
                                value += "<li>"+result.items[index].volumeInfo.authors[i]+"</li>";
                               }
                            //    $("#data").append("</td></ul>");
                               value += "</ul></td>";

                            }
                            if (result.items[index].volumeInfo.description==undefined) {
                                value += "<td>"+"Tidak ada Deskripsi"+"</td>";
                                // $("#data").append("<td>"+"Tidak ada Deskripsi"+"<td>");
                            } else {
                                value += "<td>"+result.items[index].volumeInfo.description+"</td>";
                                // $("#data").append("<td>"+result.items[index].volumeInfo.description+"</td>");
                            
                            }
                            // $("#data").append("<tr>");
                            value += "</tr>";
                            $("#data").append(value);
                        }
                    }
                })
                // e.preventDefault();
            }
        )
        </script>
    </body>
</html>

jspage/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body%}
<link rel="stylesheet" href="{% static 'baseaccordion.css'%}">
<!-- Default switch -->
<body class="light" id="body">
        <div class="custom-control custom-switch" style="margin-top: 2cm;;">
                <input type="checkbox" class="custom-control-input" id="customSwitches" onclick="ubahWarna()">
                <label class="custom-control-label label" for="customSwitches">Ganti Tema</label>
              </div>
                  <h2 style="text-align: center;">Kegiatan Saya</h2>
                  <!-- <div style="width:400px; margin:0 auto;"> -->
              <div class="accordion" id="accordionExample" style="width:400px; margin:0 auto;">
                <div class="card">
                  <div class="card-header" id="headingOne">
                    <h2 class="mb-0">
                      <button class="btn collapsed" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Aktivitas
                      </button>
                    </h2>
                  </div>
              
                  <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body">
                        Saya adalah mahasiswa Ilmu Komputer, Universitas Indonesia. Saya berada di semester ke 3.
                        Aktivitas sehari-hari saya hanyalah kuliah-tidur kuliah tidur :(
                    </div>
                  </div>
                </div>
                <div class="card">
                  <div class="card-header" id="headingTwo">
                    <h2 class="mb-0">
                      <button class="btn collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Kepanitiaan
                      </button>
                    </h2>
                  </div>
                  <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body">
                      <ul>
                          <li>Pramuka 2015-2018</li>
                          <li>Panitia SIWAK NG 2019</li>
                          <li>Panitia Lomba Paskibra 2016</li>
                      </ul>
                      
                    </div>
                  </div>
                </div>
                <div class="card">
                  <div class="card-header" id="headingThree">
                    <h2 class="mb-0">
                      <button class="btn collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        Prestasi
                      </button>
                    </h2>
                  </div>
                  <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                    <div class="card-body">
                        <ul>
                            Akan ditambah secepatnya :))
                        </ul>
                    </div>
                  </div>   
                </div>
            </div>     
            
    <script>
    function ubahWarna(){
        var el = document.getElementById("body");
        if(el.className == "light") {
            el.className = "dark";
        }
        else {
            el.className = "light";
            }
        }
    </script>
  
</body>
    
{% endblock body %}

landingpage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
  <title>Selamat Datang!</title>
  <style>
    section{
      min-height: 600px;
    }
  </style>
    
</head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<body class="mt-5">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark" style="background-color:#AA0534">
    <div class="container">
      <a class="navbar-brand">Aji Inisti</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% with url_name=request.resolver_match.url_name %}
          <li>
              <a class="nav-item nav-link" role="tab" href ="{% url 'landingpage:index' %}">Status</a>
          </li>
          <li>
              <a class="nav-item nav-link" href="{% url 'jspage:index' %}">JsQuery</a>
          </li>
          {% endwith %}
        </div>
      </div>
    </div>
  </nav>
    {% block body %}
    {% endblock body %}
  
    <div class="container text-center">
          <p class="mt-4 p">Aji Inisti Udma Wijaya © 2019</p>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</body>
    

landingpage/templates/landingpage/index.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
    {% block body %}
        <style>
        td {
            overflow: hidden;
            max-width: 60px;
            word-wrap: break-word;
            }
        </style>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <body>
        <div class="row">
            <div class="col align-self-center">
                    <h1 class="text-primary">Halo, apa kabar?</h1>
                    <form method="POST">
                        {% csrf_token %}
                        {{ generated_formulir.as_p}}
                        <input type="submit" value="Klik!">
                    </form>
            </div>
        </div>
        <div class="container rounded">        
                <table style="width: 100%;" ;align="center">
                    <tr style="flex-wrap: initial;">
                        <th>Nama</th>
                        <th>Status</th>
                        <th>Waktu</th>
                    </tr>
                    {% for i in generated_model %}
                    <tr style="flex-wrap: initial;">
                        <td>{{i.nama}}</td>
                        <td>{{i.status}}</td>
                        <td>{{i.waktu}}</td>
                    </tr>
                    {% endfor %}
                </table>
        </div>
        {% endblock %}
    </body>
</html>

story10/templates/index10.html
{% load static %}
<html>
    <h1>Load Balancer</h1>
    <h2>Apa itu Load Balancer ?</h2>
    <p>Load Balancer adalah alat yang memungkinkan kita mengakses satu web yang sebenarnya load balancer memanggil tidak hanya dari satu server. Bisa dari beragam server.</p>
    <h2>Bagaimana cara kerja Load Balancer?</h2>
    <p> Cara kerja Load Balancer adalah web yang sudah dibuat urlnya akan menuju ke load balancer dimana load balancer akan mengecek semua server yang sudah di cantumkan dalam Load Balancer yang kemudian ia meminta request dari salah satu server yang ada.</p>
    <h2>Apa keuntungan Load Balancer?</h2>
    <p>Keuntungan Load Balancer adalah High Availability dari suatu web sehingga saat terdapat satu server mati maka akan diatasi dengan cara load balancer akan pindah ke port/server yang berbeda sehingga Web tetap akan bisa diakses.</p>
    <h2>Bagaimana cara menggunakan Load Balancer ?</h2>
    <h3>1. Download Load Balancer</h6>
    <p>Hal pertama yang dilakukan adalah kita harus mendownload load balancer yang ingin digunakan
    . Kalian dapat menggunakan apa saja, contoh yang akan diberikan adalah menggunakan Nginx. 
    Dapat didownload di <a href="http://nginx.org/download/nginx-1.17.6.zip">Download disini!</a>
    atau kalian dapat mendownload dengan mengakses web Nginx.org secara langsung.<img src="{% static 'images/download.PNG'%}" alt="Download">
    </p>
    <h3>2. Ekstrak Nginx</h3>
    <p>Setelah mendownload Nginx kemudian ekstrak file yang ada dan pindahkan ke dalam project yang ingin di coba 
        <img src="{% static 'images/pindahkan.PNG'%}" alt="Pindahkan"> </p>
    <h3>3. Konfigurasi nginx</h3>
    <p>Konfigurasi Nginx dengan cara membuka file nginx.config kemudian ubah di bagian http
            <img src="{% static 'images/config.PNG'%}" alt="Config"> </p>
            <img src="{% static 'images/konfigurasi.PNG'%}" alt="Konfigurasi"> </p>
    </p>
    <h3>4. Settings views.py</h3>
    <p>Setelah konfigurasi nginx, Karena kita akan menampilkan dari server/port mana load balancer akan memilih.
        Maka jangan lupa untuk mensetting views.py project yang akan ditampilkan. Cara menampilkan dari port mana dengan cara sebagai berikut
        Line 1,4,7-9
        <img src="{% static 'images/views.PNG'%}" alt="views"> </p>
    </p>
    <h3>5. Nyalakan Server</h3>
    <p>Kemudian nyalakan server dari port yang sudah ada di konfigurasi
            <img src="{% static 'images/nyalakanserver.PNG'%}" alt="TurnOnServer"> </p>
    </p>
    <h3>6. Nyalakan Nginx</h3>
    <p>Nyalakan nginx dengan cara membuka app yang ada di dalam file nginx
            <img src="{% static 'images/nyalakanNginx.PNG'%}" alt="TurnOnNginx"> </p>
    </p>
    <h3>7. Pengujian</h3>
    <p>Langkah terakhir adalah dengan cara menguji url. Dengan cara mengakses localhost kemudian merefresh atau memuat ulang localhost
            <img src="{% static 'images/runserver.PNG'%}" alt="server1"> </p>
            <img src="{% static 'images/runserver2.PNG'%}" alt="server2"> </p>
    </p>

</html>

story9/templates/story9.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    </head>
    <body style="background-color: lightpink;">
        <script src="https://code.jquery.com/jquery-1.11.3.js" ></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        
        <div class="d-flex align-items-center row justify-content-center">
                <div class="card">
                    <div class="card-body">
                    <h1 style="text-align: center;">Haloo !!</h1>
                    {% if user.is_authenticated%}
                    <div style="text-align: center;">
                        <p>Selamat datang <strong>{{user.username}}</strong></p>
                        <a href="{% url 'logout' %}" class="btn btn-secondary">Log out</a>
                    </div>
                    {% else %}
                    <div style="text-align: center;">
                    <p>Selamat datang</p>
                    <a href="{% url 'login' %}" class="btn btn-primary">Sign in</a>
                    <a href="{% url 'signup' %}" class="btn btn-primary">Sign up</a>
                    {% endif%}
                    </div>
                    </div>
                </div>
        </div>
        
    </body>
</html>